[package]
name = "megalodon_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
megalodon = "0.12.4"
serde_json = "1.0.113"
tokio = "1.36.0"
